"""add reply variants and reply_variant_id

Revision ID: 1c965b3067f5
Revises: 5319c25cfe88
Create Date: 2026-06-16 10:10:44.416487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c965b3067f5"
down_revision: Union[str, Sequence[str], None] = "5319c25cfe88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sa_industries", sa.Column("reply_variants", sa.JSON(), nullable=True)
    )
    op.add_column(
        "sa_task_queue",
        sa.Column("reply_variant_id", sa.String(length=64), nullable=True),
    )
    op.create_index(
        op.f("ix_sa_task_queue_reply_variant_id"),
        "sa_task_queue",
        ["reply_variant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sa_task_queue_reply_variant_id"), table_name="sa_task_queue")
    op.drop_column("sa_task_queue", "reply_variant_id")
    op.drop_column("sa_industries", "reply_variants")
    # ### end Alembic commands ###
