"""add phase3 scheduling and effect fields

Revision ID: 5319c25cfe88
Revises: 5b4bf33fdcdb
Create Date: 2026-06-16 08:49:04.329829

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5319c25cfe88"
down_revision: Union[str, Sequence[str], None] = "5b4bf33fdcdb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sa_industries",
        sa.Column("send_start_time", sa.String(length=8), nullable=True),
    )
    op.add_column(
        "sa_industries", sa.Column("send_end_time", sa.String(length=8), nullable=True)
    )
    op.add_column(
        "sa_industries", sa.Column("pause_weekends", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "sa_industries", sa.Column("daily_send_max", sa.Integer(), nullable=True)
    )
    op.add_column(
        "sa_industries",
        sa.Column("effect_webhook_url", sa.String(length=512), nullable=True),
    )
    op.add_column(
        "sa_task_queue", sa.Column("replied_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "sa_task_queue", sa.Column("converted_at", sa.DateTime(), nullable=True)
    )
    op.add_column("sa_task_queue", sa.Column("reply_text", sa.Text(), nullable=True))
    op.add_column(
        "sa_task_queue",
        sa.Column("conversion_value", sa.String(length=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sa_task_queue", "conversion_value")
    op.drop_column("sa_task_queue", "reply_text")
    op.drop_column("sa_task_queue", "converted_at")
    op.drop_column("sa_task_queue", "replied_at")
    op.drop_column("sa_industries", "effect_webhook_url")
    op.drop_column("sa_industries", "daily_send_max")
    op.drop_column("sa_industries", "pause_weekends")
    op.drop_column("sa_industries", "send_end_time")
    op.drop_column("sa_industries", "send_start_time")
    # ### end Alembic commands ###
