"""init thunder capture schema

Revision ID: 5b4bf33fdcdb
Revises: 
Create Date: 2026-06-16 08:37:18.662097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4bf33fdcdb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sa_action_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.String(length=64), nullable=True),
    sa.Column('consumer_id', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('target_user', sa.String(length=128), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('ai_reply', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_action_log_consumer_id'), 'sa_action_log', ['consumer_id'], unique=False)
    op.create_index(op.f('ix_sa_action_log_status'), 'sa_action_log', ['status'], unique=False)
    op.create_index(op.f('ix_sa_action_log_ts'), 'sa_action_log', ['ts'], unique=False)
    op.create_table('sa_collected_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aweme_id', sa.String(length=128), nullable=False),
    sa.Column('source_sec_uid', sa.String(length=128), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aweme_id', 'source_sec_uid', name='uix_aweme_source')
    )
    op.create_index(op.f('ix_sa_collected_videos_aweme_id'), 'sa_collected_videos', ['aweme_id'], unique=False)
    op.create_index(op.f('ix_sa_collected_videos_source_sec_uid'), 'sa_collected_videos', ['source_sec_uid'], unique=False)
    op.create_table('sa_collector_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('industry_slug', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry_slug', 'platform', 'key', name='uix_collector_state')
    )
    op.create_index(op.f('ix_sa_collector_state_industry_slug'), 'sa_collector_state', ['industry_slug'], unique=False)
    op.create_table('sa_consumer_state',
    sa.Column('consumer_id', sa.String(length=128), nullable=False),
    sa.Column('daily_sent', sa.Integer(), nullable=True),
    sa.Column('last_sent_date', sa.String(length=32), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('min_interval_sec', sa.Integer(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=True),
    sa.Column('total_failed', sa.Integer(), nullable=True),
    sa.Column('wave_sent', sa.Integer(), nullable=True),
    sa.Column('waves_today', sa.Integer(), nullable=True),
    sa.Column('rate_limited_at', sa.String(length=64), nullable=True),
    sa.Column('adaptive_limit', sa.Integer(), nullable=True),
    sa.Column('last_wave_date', sa.String(length=32), nullable=True),
    sa.Column('nurture_done_today', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('consumer_id')
    )
    op.create_table('sa_industry_daily_quota',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('industry_slug', sa.String(length=64), nullable=False),
    sa.Column('day', sa.String(length=32), nullable=False),
    sa.Column('sent', sa.Integer(), nullable=True),
    sa.Column('reserved', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry_slug', 'day', name='uix_industry_day_quota')
    )
    op.create_index(op.f('ix_sa_industry_daily_quota_day'), 'sa_industry_daily_quota', ['day'], unique=False)
    op.create_index(op.f('ix_sa_industry_daily_quota_industry_slug'), 'sa_industry_daily_quota', ['industry_slug'], unique=False)
    op.create_table('sa_target_bloggers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('industry_slug', sa.String(length=64), nullable=False),
    sa.Column('sec_uid', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('uid', sa.String(length=128), nullable=True),
    sa.Column('source_keyword', sa.String(length=128), nullable=True),
    sa.Column('source_video_id', sa.String(length=128), nullable=True),
    sa.Column('discovered_at', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry_slug', 'sec_uid', name='uix_industry_sec_uid')
    )
    op.create_index(op.f('ix_sa_target_bloggers_industry_slug'), 'sa_target_bloggers', ['industry_slug'], unique=False)
    op.create_index(op.f('ix_sa_target_bloggers_sec_uid'), 'sa_target_bloggers', ['sec_uid'], unique=False)
    op.create_index(op.f('ix_sa_target_bloggers_status'), 'sa_target_bloggers', ['status'], unique=False)
    op.create_table('sa_task_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('industry_slug', sa.String(length=64), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('keyword', sa.String(length=128), nullable=True),
    sa.Column('video_id', sa.String(length=128), nullable=False),
    sa.Column('video_url', sa.String(length=256), nullable=True),
    sa.Column('comment_id', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('user_name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('matched_categories', sa.String(length=512), nullable=True),
    sa.Column('fetched_at', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('consumer_id', sa.String(length=128), nullable=True),
    sa.Column('claim_token', sa.String(length=128), nullable=True),
    sa.Column('claimed_at', sa.String(length=64), nullable=True),
    sa.Column('processed_at', sa.String(length=64), nullable=True),
    sa.Column('ai_reply', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('short_id', sa.String(length=128), nullable=True),
    sa.Column('douyin_id', sa.String(length=128), nullable=True),
    sa.Column('unique_id', sa.String(length=128), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('retry_after', sa.String(length=64), nullable=True),
    sa.Column('source_keyword', sa.String(length=128), nullable=True),
    sa.Column('source_creator', sa.String(length=128), nullable=True),
    sa.Column('source_video_desc', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.String(length=64), nullable=True),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'video_id', name='uix_comment_video')
    )
    op.create_index(op.f('ix_sa_task_queue_comment_id'), 'sa_task_queue', ['comment_id'], unique=False)
    op.create_index(op.f('ix_sa_task_queue_consumer_id'), 'sa_task_queue', ['consumer_id'], unique=False)
    op.create_index(op.f('ix_sa_task_queue_industry_slug'), 'sa_task_queue', ['industry_slug'], unique=False)
    op.create_index(op.f('ix_sa_task_queue_job_id'), 'sa_task_queue', ['job_id'], unique=False)
    op.create_index(op.f('ix_sa_task_queue_owner_user_id'), 'sa_task_queue', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_sa_task_queue_status'), 'sa_task_queue', ['status'], unique=False)
    op.create_index(op.f('ix_sa_task_queue_video_id'), 'sa_task_queue', ['video_id'], unique=False)
    op.create_table('sa_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deepseek_key', sa.String(length=128), nullable=True),
    sa.Column('zhipu_key', sa.String(length=128), nullable=True),
    sa.Column('openai_key', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_users_username'), 'sa_users', ['username'], unique=True)
    op.create_table('sa_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('adb_serial', sa.String(length=128), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('min_interval_sec', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('runtime_status', sa.String(length=32), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('last_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('keyboard_ready', sa.Boolean(), nullable=True),
    sa.Column('keyboard_message', sa.String(length=256), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('last_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_devices_last_job_id'), 'sa_devices', ['last_job_id'], unique=False)
    op.create_index(op.f('ix_sa_devices_user_id'), 'sa_devices', ['user_id'], unique=False)
    op.create_table('sa_industries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('reply_tone', sa.String(length=64), nullable=True),
    sa.Column('reply_style', sa.String(length=256), nullable=True),
    sa.Column('reply_hook', sa.String(length=256), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('video_max_age_days', sa.Integer(), nullable=True),
    sa.Column('comment_max_age_hours', sa.Integer(), nullable=True),
    sa.Column('llm_provider', sa.String(length=32), nullable=True),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('intent_keywords', sa.JSON(), nullable=True),
    sa.Column('noise_keywords', sa.JSON(), nullable=True),
    sa.Column('target_users', sa.JSON(), nullable=True),
    sa.Column('matrix_target_devices', sa.Integer(), nullable=True),
    sa.Column('lead_inventory_days', sa.Integer(), nullable=True),
    sa.Column('global_daily_limit', sa.Integer(), nullable=True),
    sa.Column('auto_replenish_enabled', sa.Boolean(), nullable=True),
    sa.Column('replenish_threshold_days', sa.Integer(), nullable=True),
    sa.Column('keyword_batch_size', sa.Integer(), nullable=True),
    sa.Column('collect_authors_per_run', sa.Integer(), nullable=True),
    sa.Column('collect_video_limit', sa.Integer(), nullable=True),
    sa.Column('compliance_mode', sa.Boolean(), nullable=True),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.Column('auto_export_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_industries_user_id'), 'sa_industries', ['user_id'], unique=False)
    op.create_table('sa_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('industry_slug', sa.String(length=64), nullable=True),
    sa.Column('industry_name', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_jobs_created_at'), 'sa_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sa_jobs_industry_slug'), 'sa_jobs', ['industry_slug'], unique=False)
    op.create_index(op.f('ix_sa_jobs_status'), 'sa_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_sa_jobs_type'), 'sa_jobs', ['type'], unique=False)
    op.create_index(op.f('ix_sa_jobs_user_id'), 'sa_jobs', ['user_id'], unique=False)
    op.create_table('sa_agent_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('industry_slug', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('subject_type', sa.String(length=64), nullable=True),
    sa.Column('subject_id', sa.String(length=128), nullable=True),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['sa_devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_agent_memory_created_at'), 'sa_agent_memory', ['created_at'], unique=False)
    op.create_index(op.f('ix_sa_agent_memory_device_id'), 'sa_agent_memory', ['device_id'], unique=False)
    op.create_index(op.f('ix_sa_agent_memory_industry_slug'), 'sa_agent_memory', ['industry_slug'], unique=False)
    op.create_index(op.f('ix_sa_agent_memory_memory_type'), 'sa_agent_memory', ['memory_type'], unique=False)
    op.create_index(op.f('ix_sa_agent_memory_subject_id'), 'sa_agent_memory', ['subject_id'], unique=False)
    op.create_index(op.f('ix_sa_agent_memory_subject_type'), 'sa_agent_memory', ['subject_type'], unique=False)
    op.create_index(op.f('ix_sa_agent_memory_user_id'), 'sa_agent_memory', ['user_id'], unique=False)
    op.create_table('sa_device_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_app', sa.String(length=64), nullable=True),
    sa.Column('current_screen', sa.String(length=128), nullable=True),
    sa.Column('health', sa.JSON(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['sa_devices.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['sa_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_device_state_device_id'), 'sa_device_state', ['device_id'], unique=False)
    op.create_index(op.f('ix_sa_device_state_job_id'), 'sa_device_state', ['job_id'], unique=False)
    op.create_index(op.f('ix_sa_device_state_last_heartbeat'), 'sa_device_state', ['last_heartbeat'], unique=False)
    op.create_index(op.f('ix_sa_device_state_status'), 'sa_device_state', ['status'], unique=False)
    op.create_index(op.f('ix_sa_device_state_user_id'), 'sa_device_state', ['user_id'], unique=False)
    op.create_table('sa_execution_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['sa_devices.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['sa_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_execution_logs_action'), 'sa_execution_logs', ['action'], unique=False)
    op.create_index(op.f('ix_sa_execution_logs_created_at'), 'sa_execution_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sa_execution_logs_device_id'), 'sa_execution_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_sa_execution_logs_job_id'), 'sa_execution_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_sa_execution_logs_status'), 'sa_execution_logs', ['status'], unique=False)
    op.create_index(op.f('ix_sa_execution_logs_user_id'), 'sa_execution_logs', ['user_id'], unique=False)
    op.create_table('sa_screen_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('screen_name', sa.String(length=128), nullable=True),
    sa.Column('blocker', sa.String(length=64), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ui_tree', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['sa_devices.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['sa_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_screen_snapshots_captured_at'), 'sa_screen_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_sa_screen_snapshots_device_id'), 'sa_screen_snapshots', ['device_id'], unique=False)
    op.create_index(op.f('ix_sa_screen_snapshots_job_id'), 'sa_screen_snapshots', ['job_id'], unique=False)
    op.create_index(op.f('ix_sa_screen_snapshots_screen_name'), 'sa_screen_snapshots', ['screen_name'], unique=False)
    op.create_index(op.f('ix_sa_screen_snapshots_task_id'), 'sa_screen_snapshots', ['task_id'], unique=False)
    op.create_index(op.f('ix_sa_screen_snapshots_user_id'), 'sa_screen_snapshots', ['user_id'], unique=False)
    op.create_table('sa_task_graphs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('industry_slug', sa.String(length=64), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('graph', sa.JSON(), nullable=True),
    sa.Column('retry_policy', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['sa_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_task_graphs_created_at'), 'sa_task_graphs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sa_task_graphs_industry_slug'), 'sa_task_graphs', ['industry_slug'], unique=False)
    op.create_index(op.f('ix_sa_task_graphs_job_id'), 'sa_task_graphs', ['job_id'], unique=False)
    op.create_index(op.f('ix_sa_task_graphs_status'), 'sa_task_graphs', ['status'], unique=False)
    op.create_index(op.f('ix_sa_task_graphs_task_type'), 'sa_task_graphs', ['task_type'], unique=False)
    op.create_index(op.f('ix_sa_task_graphs_user_id'), 'sa_task_graphs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sa_task_graphs_user_id'), table_name='sa_task_graphs')
    op.drop_index(op.f('ix_sa_task_graphs_task_type'), table_name='sa_task_graphs')
    op.drop_index(op.f('ix_sa_task_graphs_status'), table_name='sa_task_graphs')
    op.drop_index(op.f('ix_sa_task_graphs_job_id'), table_name='sa_task_graphs')
    op.drop_index(op.f('ix_sa_task_graphs_industry_slug'), table_name='sa_task_graphs')
    op.drop_index(op.f('ix_sa_task_graphs_created_at'), table_name='sa_task_graphs')
    op.drop_table('sa_task_graphs')
    op.drop_index(op.f('ix_sa_screen_snapshots_user_id'), table_name='sa_screen_snapshots')
    op.drop_index(op.f('ix_sa_screen_snapshots_task_id'), table_name='sa_screen_snapshots')
    op.drop_index(op.f('ix_sa_screen_snapshots_screen_name'), table_name='sa_screen_snapshots')
    op.drop_index(op.f('ix_sa_screen_snapshots_job_id'), table_name='sa_screen_snapshots')
    op.drop_index(op.f('ix_sa_screen_snapshots_device_id'), table_name='sa_screen_snapshots')
    op.drop_index(op.f('ix_sa_screen_snapshots_captured_at'), table_name='sa_screen_snapshots')
    op.drop_table('sa_screen_snapshots')
    op.drop_index(op.f('ix_sa_execution_logs_user_id'), table_name='sa_execution_logs')
    op.drop_index(op.f('ix_sa_execution_logs_status'), table_name='sa_execution_logs')
    op.drop_index(op.f('ix_sa_execution_logs_job_id'), table_name='sa_execution_logs')
    op.drop_index(op.f('ix_sa_execution_logs_device_id'), table_name='sa_execution_logs')
    op.drop_index(op.f('ix_sa_execution_logs_created_at'), table_name='sa_execution_logs')
    op.drop_index(op.f('ix_sa_execution_logs_action'), table_name='sa_execution_logs')
    op.drop_table('sa_execution_logs')
    op.drop_index(op.f('ix_sa_device_state_user_id'), table_name='sa_device_state')
    op.drop_index(op.f('ix_sa_device_state_status'), table_name='sa_device_state')
    op.drop_index(op.f('ix_sa_device_state_last_heartbeat'), table_name='sa_device_state')
    op.drop_index(op.f('ix_sa_device_state_job_id'), table_name='sa_device_state')
    op.drop_index(op.f('ix_sa_device_state_device_id'), table_name='sa_device_state')
    op.drop_table('sa_device_state')
    op.drop_index(op.f('ix_sa_agent_memory_user_id'), table_name='sa_agent_memory')
    op.drop_index(op.f('ix_sa_agent_memory_subject_type'), table_name='sa_agent_memory')
    op.drop_index(op.f('ix_sa_agent_memory_subject_id'), table_name='sa_agent_memory')
    op.drop_index(op.f('ix_sa_agent_memory_memory_type'), table_name='sa_agent_memory')
    op.drop_index(op.f('ix_sa_agent_memory_industry_slug'), table_name='sa_agent_memory')
    op.drop_index(op.f('ix_sa_agent_memory_device_id'), table_name='sa_agent_memory')
    op.drop_index(op.f('ix_sa_agent_memory_created_at'), table_name='sa_agent_memory')
    op.drop_table('sa_agent_memory')
    op.drop_index(op.f('ix_sa_jobs_user_id'), table_name='sa_jobs')
    op.drop_index(op.f('ix_sa_jobs_type'), table_name='sa_jobs')
    op.drop_index(op.f('ix_sa_jobs_status'), table_name='sa_jobs')
    op.drop_index(op.f('ix_sa_jobs_industry_slug'), table_name='sa_jobs')
    op.drop_index(op.f('ix_sa_jobs_created_at'), table_name='sa_jobs')
    op.drop_table('sa_jobs')
    op.drop_index(op.f('ix_sa_industries_user_id'), table_name='sa_industries')
    op.drop_table('sa_industries')
    op.drop_index(op.f('ix_sa_devices_user_id'), table_name='sa_devices')
    op.drop_index(op.f('ix_sa_devices_last_job_id'), table_name='sa_devices')
    op.drop_table('sa_devices')
    op.drop_index(op.f('ix_sa_users_username'), table_name='sa_users')
    op.drop_table('sa_users')
    op.drop_index(op.f('ix_sa_task_queue_video_id'), table_name='sa_task_queue')
    op.drop_index(op.f('ix_sa_task_queue_status'), table_name='sa_task_queue')
    op.drop_index(op.f('ix_sa_task_queue_owner_user_id'), table_name='sa_task_queue')
    op.drop_index(op.f('ix_sa_task_queue_job_id'), table_name='sa_task_queue')
    op.drop_index(op.f('ix_sa_task_queue_industry_slug'), table_name='sa_task_queue')
    op.drop_index(op.f('ix_sa_task_queue_consumer_id'), table_name='sa_task_queue')
    op.drop_index(op.f('ix_sa_task_queue_comment_id'), table_name='sa_task_queue')
    op.drop_table('sa_task_queue')
    op.drop_index(op.f('ix_sa_target_bloggers_status'), table_name='sa_target_bloggers')
    op.drop_index(op.f('ix_sa_target_bloggers_sec_uid'), table_name='sa_target_bloggers')
    op.drop_index(op.f('ix_sa_target_bloggers_industry_slug'), table_name='sa_target_bloggers')
    op.drop_table('sa_target_bloggers')
    op.drop_index(op.f('ix_sa_industry_daily_quota_industry_slug'), table_name='sa_industry_daily_quota')
    op.drop_index(op.f('ix_sa_industry_daily_quota_day'), table_name='sa_industry_daily_quota')
    op.drop_table('sa_industry_daily_quota')
    op.drop_table('sa_consumer_state')
    op.drop_index(op.f('ix_sa_collector_state_industry_slug'), table_name='sa_collector_state')
    op.drop_table('sa_collector_state')
    op.drop_index(op.f('ix_sa_collected_videos_source_sec_uid'), table_name='sa_collected_videos')
    op.drop_index(op.f('ix_sa_collected_videos_aweme_id'), table_name='sa_collected_videos')
    op.drop_table('sa_collected_videos')
    op.drop_index(op.f('ix_sa_action_log_ts'), table_name='sa_action_log')
    op.drop_index(op.f('ix_sa_action_log_status'), table_name='sa_action_log')
    op.drop_index(op.f('ix_sa_action_log_consumer_id'), table_name='sa_action_log')
    op.drop_table('sa_action_log')
    # ### end Alembic commands ###
