"""add task queue composite indexes

Revision ID: 81fe0505b506
Revises: 1c965b3067f5
Create Date: 2026-06-16 14:17:32.233450

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '81fe0505b506'
down_revision: Union[str, Sequence[str], None] = '1c965b3067f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_task_queue_fetched_at', 'sa_task_queue', ['fetched_at'], unique=False)
    op.create_index('ix_task_queue_industry_status', 'sa_task_queue', ['industry_slug', 'status'], unique=False)
    op.create_index('ix_task_queue_industry_status_owner', 'sa_task_queue', ['industry_slug', 'status', 'owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_queue_industry_status_owner', table_name='sa_task_queue')
    op.drop_index('ix_task_queue_industry_status', table_name='sa_task_queue')
    op.drop_index('ix_task_queue_fetched_at', table_name='sa_task_queue')
    # ### end Alembic commands ###
